config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'posts#index'
end

app/models/application_record.rb
# ApplicationRecord はモデル操作の既定となるクラス
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
# Post はブログのひとつの投稿を表すモデル
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true
end

app/controllers/application_controller.rb
# ApplicationController はすべてのControllerの基底クラス
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
# PostsController は /posts から始まるURLを処理する
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts もしくは GET /posts.json のリクエストが発生した時の処理
  def index
    @posts = Post.all
  end

  # GET /posts/:id もしくは GET /posts/:id.json のリクエストが発生した時の処理
  def show; end

  # GET /posts/new のリクエストが発生した時の処理
  def new
    @post = Post.new
  end

  # GET /posts/:id/edit のリクエストが発生した時の処理
  def edit; end

  # POST /posts もしくは POST /posts.json のリクエストが発生した時の処理
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: t('.success') }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/:id もしくは PATCH /posts/:id.json のリクエストが発生した時の処理
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: t('.success') }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/:id もしくは /posts/:id.json のリクエストが発生した時の処理
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: t('.success') }
      format.json { head :no_content }
    end
  end

  private

  # URL内に:idが含まれている場合、それをキーにしてPostを検索し、@post に格納する
  # @return [Post] :idを主キーとするPostのインスタンス
  def set_post
    @post = Post.find(params[:id])
  end

  # 外部から与えられたリクエストパラメータのうち、許可するもののリストを定義する
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
# ApplicationHelper はすべての画面に共通なヘルパー関数
module ApplicationHelper
end

app/helpers/posts_helper.rb
# PostsHelper はPostsのView固有のヘルパー関数
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Rails Template</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body id='<%= "#{controller.controller_name}_#{controller.action_name}" %>'>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Rails Template</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit 'Create/Update Post', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post, class: 'btn btn-primary' %> |
  <%= link_to "Back to posts", posts_path, class: 'btn btn-primary' %>
</div>

app/views/posts/index.html.erb
<% if notice.present? %>
  <p class="alert alert-primary"><%= notice %></p>
<% end %>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post, class: 'btn btn-primary' %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path, class: 'btn btn-primary' %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path, class: 'btn btn-primary' %>
</div>

app/views/posts/show.html.erb
<% if notice.present? %>
  <p class="alert alert-primary"><%= notice %></p>
<% end %>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post), class: 'btn btn-primary' %> |
  <%= link_to "Back to posts", posts_path, class: 'btn btn-primary' %>

  <%= button_to "Destroy this post", @post, {method: :delete, class: 'btn btn-primary'} %>
</div>